<a href="https://colab.research.google.com/github/yerinnne/WorkSpace/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0%EC%9C%BC%EB%A1%9C_%EC%8B%9C%EC%9E%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import sklearn

In [54]:
#help(sklearn)

In [55]:
print(sklearn.__version__)

1.2.2


## 02 첫 번째 머신러닝 - 붓꽃 품종 예측하기 (iris)

In [56]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [57]:
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [13]:
iris.keys() #key값 확인

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [14]:
iris_data = iris.data
iris_data.shape

(150, 4)

In [17]:
iris_label = iris.target # 종속변수 의미

In [18]:
np.unique(iris_label, return_counts = True)

(array([0, 1, 2]), array([50, 50, 50]))

In [19]:
iris.target_names #종속변수명

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [21]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [23]:
xa = [[x,x] for x in range(100)]
ya = [y for y in range(100)]

In [25]:
# ttrain_test_split : 학습 데이터와 테스트 데이터 셔플 후 분리
x_train, x_test, y_train, y_test = train_test_split(xa,ya)

In [28]:
np.array(x_train).shape,  np.array(y_train).shape #학습데이터 75: 테스트데이터 25

((75, 2), (75,))

In [27]:
for i in range(len(x_train)):
  print(x_train[i],':',y_train[i])

[0, 0] : 0
[82, 82] : 82
[83, 83] : 83
[39, 39] : 39
[30, 30] : 30
[43, 43] : 43
[48, 48] : 48
[71, 71] : 71
[50, 50] : 50
[16, 16] : 16
[87, 87] : 87
[67, 67] : 67
[32, 32] : 32
[20, 20] : 20
[35, 35] : 35
[88, 88] : 88
[60, 60] : 60
[89, 89] : 89
[94, 94] : 94
[37, 37] : 37
[5, 5] : 5
[28, 28] : 28
[19, 19] : 19
[74, 74] : 74
[45, 45] : 45
[86, 86] : 86
[92, 92] : 92
[65, 65] : 65
[68, 68] : 68
[90, 90] : 90
[59, 59] : 59
[44, 44] : 44
[29, 29] : 29
[10, 10] : 10
[1, 1] : 1
[14, 14] : 14
[49, 49] : 49
[77, 77] : 77
[3, 3] : 3
[99, 99] : 99
[4, 4] : 4
[81, 81] : 81
[75, 75] : 75
[53, 53] : 53
[22, 22] : 22
[23, 23] : 23
[25, 25] : 25
[38, 38] : 38
[69, 69] : 69
[36, 36] : 36
[98, 98] : 98
[93, 93] : 93
[84, 84] : 84
[78, 78] : 78
[85, 85] : 85
[61, 61] : 61
[27, 27] : 27
[55, 55] : 55
[26, 26] : 26
[79, 79] : 79
[33, 33] : 33
[64, 64] : 64
[41, 41] : 41
[31, 31] : 31
[96, 96] : 96
[24, 24] : 24
[18, 18] : 18
[6, 6] : 6
[12, 12] : 12
[46, 46] : 46
[11, 11] : 11
[2, 2] : 2
[13, 13] : 13

In [32]:
x_train, x_test, y_train, y_test = train_test_split(
    iris_data, iris_label, test_size = 0.2) # 4:1 비율로 변경(디폴트 3:1)

In [35]:
x_train.shape, x_test.shape

((120, 4), (30, 4))

In [36]:
model = DecisionTreeClassifier() # 모델 생성
model.fit(x_train, y_train) # 모델 학습(머신러닝 모델에서 기계학습은 fit 사용)

DecisionTreeClassifier()

In [37]:
pred = model.predict(x_test) # 학습한 모델로 예측->모델 학습 결과 평가

In [41]:
for i in range(len(pred)):
  print(pred[i], ':', y_test[i])

print(pred)
print(y_test)

1 : 1
0 : 0
0 : 0
0 : 0
2 : 1
1 : 1
2 : 2
0 : 0
2 : 2
1 : 1
2 : 2
2 : 1
2 : 2
2 : 2
0 : 0
1 : 1
2 : 2
2 : 2
0 : 0
1 : 2
1 : 1
1 : 1
0 : 0
2 : 2
0 : 0
1 : 2
0 : 0
1 : 1
0 : 0
1 : 1
[1 0 0 0 2 1 2 0 2 1 2 2 2 2 0 1 2 2 0 1 1 1 0 2 0 1 0 1 0 1]
[1 0 0 0 1 1 2 0 2 1 2 1 2 2 0 1 2 2 0 2 1 1 0 2 0 2 0 1 0 1]


In [42]:
from sklearn.metrics import accuracy_score # 적합도 검정

In [44]:
print('예측 정확도 :', accuracy_score(y_test, pred)) # 모델 평가

예측 정확도 : 0.8666666666666667


# 03 사이킷런의 기반 프레임워크(91.pg)

In [61]:
iris_data = load_iris()

In [62]:
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [63]:
keys = iris_data.keys()

In [64]:
print('특성:', iris_data.feature_names)

특성: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [65]:
print('독립변수 구조:',iris_data.data.shape)

독립변수 구조: (150, 4)


In [66]:
print('종속변수 타입:',type(iris_data.target[0]))

종속변수 타입: <class 'numpy.int64'>


# Model Selection 모듈 소개

In [67]:
iris = load_iris()
train_data = iris.data #독립변수(data.feature, x)
train_label = iris.target # 종속변수(lavel.target, y)

In [69]:
df = DecisionTreeClassifier()
df.fit(train_data, train_label)
pred = df.predict(train_data) # 예측
accuracy_score(pred, train_label)

1.0

In [71]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target)

In [77]:
model = DecisionTreeClassifier() # 모델 생성
model.fit(x_train, y_train) # 모델 학습
pred = model.predict(x_test)
accuracy_score(y_test , pred) #평가

0.9473684210526315

# K 폴드 교차 검증

In [79]:
from sklearn.model_selection import KFold

In [80]:
iris = load_iris()
feature = iris.data
label = iris.target

In [81]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits = 5)

In [82]:
cv_accuracy=[]
n_iter = 0 #반복횟수

In [86]:
for train_ind, val_ind in kfold.split(feature):
  x_train, x_val = feature[train_ind], feature[val_ind]
  y_train, y_val = label[train_ind], label[val_ind]

  df.fit(x_train, y_train) #학습
  pred = df.predict(x_val)  #예측

  n_iter += 1 # 반복 횟수 1씩 증가
  acc = np.round(accuracy_score(pred, y_val),3) # 정확도
  print(n_iter, '회 교차 검증 accuracy:', acc)
  cv_accuracy.append(acc)
  print('평균 accuracy:', np.mean(cv_accuracy))

1 회 교차 검증 accuracy: 1.0
평균 accuracy: 1.0
2 회 교차 검증 accuracy: 1.0
평균 accuracy: 1.0
3 회 교차 검증 accuracy: 0.867
평균 accuracy: 0.9556666666666667
4 회 교차 검증 accuracy: 0.933
평균 accuracy: 0.95
5 회 교차 검증 accuracy: 0.733
평균 accuracy: 0.9065999999999999


In [97]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['label'] = iris.target
df['label'].value_counts()
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [98]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=3)
n_iter = 0
xdf = df.drop('label',axis=1)

for train_ind,val_ind in kfold.split(df):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]

  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측

  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 1    50
2    50
Name: label, dtype: int64
검증 데이터: 0    50
Name: label, dtype: int64
평가 accuracy: 0.0
2 ====
학습 데이터: 0    50
2    50
Name: label, dtype: int64
검증 데이터: 1    50
Name: label, dtype: int64
평가 accuracy: 0.0
3 ====
학습 데이터: 0    50
1    50
Name: label, dtype: int64
검증 데이터: 2    50
Name: label, dtype: int64
평가 accuracy: 0.0


# Stratified K 폴드

In [101]:
from sklearn.model_selection import StratifiedKFold

In [102]:
dt = DecisionTreeClassifier()
kfold = StratifiedKFold(n_splits=3)
n_iter = 0
xdf = df.drop('label',axis=1)

for train_ind, val_ind in kfold.split(df, df['label']):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]

  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측

  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 2    34
0    33
1    33
Name: label, dtype: int64
검증 데이터: 0    17
1    17
2    16
Name: label, dtype: int64
평가 accuracy: 0.98
2 ====
학습 데이터: 1    34
0    33
2    33
Name: label, dtype: int64
검증 데이터: 0    17
2    17
1    16
Name: label, dtype: int64
평가 accuracy: 0.92
3 ====
학습 데이터: 0    34
1    33
2    33
Name: label, dtype: int64
검증 데이터: 1    17
2    17
0    16
Name: label, dtype: int64
평가 accuracy: 1.0


# 교차 검증을 보다 간편하게  : cross_val_score

In [107]:
from sklearn.model_selection import cross_val_score, cross_validate

In [108]:
data = iris.data
label = iris.target

In [113]:
dt = DecisionTreeClassifier()
scores = cross_val_score(dt, data, label, scoring = 'accuracy', cv = 3)
scores

array([0.98, 0.94, 0.96])

# GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝

In [114]:
x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target)

In [116]:
mds = [1,2,3]
mss = [2,3,4]
for depth in mds:
  for ms in mss:
    dt = DecisionTreeClassifier(max_depth=depth,min_samples_split=ms)
    dt.fit(x_train,y_train)
    pred = dt.predict(x_test)
    print(depth,",",ms,": acc =",accuracy_score(y_test,pred))

1 , 2 : acc = 0.631578947368421
1 , 3 : acc = 0.631578947368421
1 , 4 : acc = 0.631578947368421
2 , 2 : acc = 0.9736842105263158
2 , 3 : acc = 0.9736842105263158
2 , 4 : acc = 0.9736842105263158
3 , 2 : acc = 0.9473684210526315
3 , 3 : acc = 0.9473684210526315
3 , 4 : acc = 0.9473684210526315


In [119]:
params = {
    'max_depth':[1,2,3],
    'min_samples_split':[2,3,4]
}

In [120]:
from sklearn.model_selection import GridSearchCV

In [121]:
dt = DecisionTreeClassifier()
gs = GridSearchCV(dt, param_grid = params, cv = 3, refit =True)
gs.fit(x_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3],
                         'min_samples_split': [2, 3, 4]})

In [123]:
gs.best_params_ # 학습 결과

{'max_depth': 2, 'min_samples_split': 2}

In [124]:
gs.best_score_

0.9376481744902798

In [125]:
model = gs.best_estimator_

In [128]:
pred = model.predict(x_test)
accuracy_score(y_test, pred)

0.9736842105263158

# 전처리

In [147]:
from sklearn.preprocessing import LabelEncoder

In [148]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [149]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items) # 레이블 인코딩 수행
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [150]:
items2 = ['TV','TV','냉장고','냉장고']
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [151]:
#items3= ['식기세척기','스타일러','냉장고']
#labels = encoder.transform(items3)
#labels

In [152]:
from sklearn.preprocessing import OneHotEncoder

In [157]:
items = np.array(items).reshape(-1,1) #2차원 배열로 변경

In [158]:
one = OneHotEncoder()
one.fit(items)
labels = one.transform(items)
labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [159]:
from scipy import stats

In [165]:
heights = stats.norm.rvs(loc = 173, scale = 4, size = 1000)
bmis = stats.norm.rvs(loc = 21, scale = 2, size = 1000)
weights = bmis*(heights**2)/10000

In [168]:
c_size = [(heights[i]*2+weights[i]*2)/5 for i in range(1000)]
c_size = np.array(c_size)

In [170]:
from sklearn.neighbors import KNeighborsRegressor

In [171]:
df = pd.DataFrame()
df['height'] = heights
df['weight'] = weights
data = df.values

In [174]:
label = c_size

In [176]:
x_train, x_test, y_train, y_test = train_test_split(data,label) #학습/테스트 데이터로 분리

In [177]:
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [178]:
knn.score(x_test, y_test)

0.9974717619715652

In [179]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [182]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [183]:
df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [184]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [186]:
ss= StandardScaler()
ss.fit(df)
scaled = ss.transform(df)
np.round(scaled.mean(),10)

-0.0

In [190]:
df2 = pd.DataFrame(scaled)
filter = df2[0]<-3
filter.value_counts()

False    150
Name: 0, dtype: int64

In [193]:
mms = MinMaxScaler()
mms.fit(data)
scaled_data = mms.transform(data)

x_train, x_test, y_train, y_test = train_test_split(scaled_data,label)
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9973891669787708

In [195]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [202]:
mms1 = MinMaxScaler()
mms1.fit(x_train)
scaled_train = mms1.transform(x_train)

In [203]:
mms2 = MinMaxScaler()
mms2.fit(x_test)
scaled_test = mms2.transform(x_test)


In [206]:
sample = [[1.75,89],[1.72,62]]
mms1.transform(sample)

array([[-5.88460386,  1.07848019],
       [-5.88571831,  0.40538843]])

In [207]:
mms.transform(sample)

array([[-6.30100187,  1.02126444],
       [-6.30219576,  0.37058556]])